"""Wire the Roboflow concrete-defect export into this project's conventions.

Source: "Concrete defect detection" by SHM, Roboflow Universe, CC BY 4.0.
1,680 images / 3,565 boxes / 6 classes, already in YOLO format with a
train/valid/test split, so unlike every other prepare_*.py there is no format
conversion to do - no VOC XML to parse, no masks to threshold. This script only
does the two things the export cannot know about:

  1. **Renames the classes.** Roboflow ships `Exposed_reinforcement`,
     `Ruststrain`, `Scaling`, `Spalling`, `crack`, `efflorescence`. The corpus
     keys are snake_case English (`exposed_reinforcement`, `rust_stain`, ...),
     and `class_texts_for` looks classes up by name. Indices are UNCHANGED, so
     no label file is rewritten - see CONCRETE_CLASSES in tgfem/data.py.
  2. **Writes manifests at the dataset ROOT.** Ultralytics resolves a manifest's
     relative paths against the manifest's own directory, so a manifest listing
     `./images/x.jpg` from inside `splits/` resolves to `splits/images/` and
     silently finds nothing. Every other dataset here hit that once; this one
     does not, because the manifests go at the root.

Audit before trusting it (0 empty, 0 malformed, 0 orphans at time of writing):
    python scripts/verify_labels.py --dataset concrete

Run:
    python scripts/prepare_concrete.py
"""

import shutil
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import yaml  # noqa: E402

from tgfem.data import CONCRETE_CLASSES  # noqa: E402

SRC = REPO_ROOT / "datasets" / "concrete-defect-roboflow"
OUT = REPO_ROOT / "datasets" / "concrete-yolo"

# Roboflow split name -> ours. Their "valid" is our "val".
SPLITS = {"train": "train", "valid": "val", "test": "test"}


def main():
    if not (SRC / "data.yaml").exists():
        raise SystemExit(
            f"missing {SRC / 'data.yaml'}\n"
            "Download the dataset from Roboflow Universe in YOLOv11 format and\n"
            f"extract it to {SRC}"
        )

    src_names = yaml.safe_load((SRC / "data.yaml").read_text())["names"]
    if len(src_names) != len(CONCRETE_CLASSES):
        raise SystemExit(
            f"export has {len(src_names)} classes {src_names}, but CONCRETE_CLASSES "
            f"has {len(CONCRETE_CLASSES)}. The rename map in tgfem/data.py is stale - "
            "fix it rather than letting indices drift."
        )

    print("=" * 62)
    print("Concrete structural defects - Roboflow export -> project layout")
    print("=" * 62)
    print("class rename (indices unchanged):")
    for i, (old, new) in enumerate(zip(src_names, CONCRETE_CLASSES)):
        print(f"  {i}  {old:<24} -> {new}")
    print()

    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "images").mkdir(parents=True)
    (OUT / "labels").mkdir(parents=True)

    counts, per_class = {}, Counter()
    boxes = empty = 0
    for src_split, our_split in SPLITS.items():
        written = []
        for img in sorted((SRC / src_split / "images").glob("*")):
            if img.suffix.lower() not in {".jpg", ".jpeg", ".png", ".bmp"}:
                continue
            lbl = SRC / src_split / "labels" / f"{img.stem}.txt"
            if not lbl.exists():
                continue
            # Roboflow stems are already globally unique (they carry a hash
            # suffix), but prefix anyway so a future re-export cannot collide
            # with what is already here.
            stem = f"{our_split}_{img.stem}"
            shutil.copy2(img, OUT / "images" / f"{stem}{img.suffix}")
            shutil.copy2(lbl, OUT / "labels" / f"{stem}.txt")

            rows = [r for r in lbl.read_text().strip().splitlines() if r.strip()]
            if not rows:
                empty += 1
            for r in rows:
                per_class[CONCRETE_CLASSES[int(r.split()[0])]] += 1
                boxes += 1
            written.append(f"./images/{stem}{img.suffix}")

        (OUT / f"{our_split}.txt").write_text("\n".join(sorted(written)) + "\n")
        counts[our_split] = len(written)
        print(f"  {our_split:<6} {len(written):>5} images")

    print(f"\ntotal boxes: {boxes}")
    if empty:
        print(f"background images (no boxes): {empty}")
    print("\nboxes per class:")
    for c in CONCRETE_CLASSES:
        print(f"  {c:<24} {per_class[c]:>5}")
    thin = [c for c in CONCRETE_CLASSES if per_class[c] < 250]
    if thin:
        print(f"\n  NOTE: {', '.join(thin)} have under 250 boxes each. Expect weak")
        print("  AP on those - the same pattern as rolled_pit (0.197) in GC10.")

    names = "\n".join(f"  {i}: {c}" for i, c in enumerate(CONCRETE_CLASSES))
    (OUT / "concrete_closed.yaml").write_text(
        "# Generated by scripts/prepare_concrete.py - do not edit by hand.\n"
        "# Source: Roboflow Universe 'Concrete defect detection' by SHM, CC BY 4.0\n"
        "# https://universe.roboflow.com/shm-agftj/concrete-defect-detection-pl8ed\n"
        "# Class INDICES are the export's own; only the names are ours.\n\n"
        f"path: {OUT.as_posix()}\n"
        "train: train.txt\n"
        "val: val.txt\n"
        "test: test.txt\n\n"
        f"names:\n{names}\n"
    )
    print(f"\nOutput: {OUT}\nDone.\n")


if __name__ == "__main__":
    main()
