"""Phase 7 (optional) - merge NEU-DET and GC10-DET into one 16-class dataset.

Motivation: Phase 7 found the text interface matches words rather than meaning,
and diagnosed it as data starvation (1,075 images / 6 classes). More classes and
more images is the cheapest available test of that diagnosis, and a richer
vocabulary makes the demo respond to more of what a user might type.

Expectations, stated up front so the result can be judged honestly:
  * mAP on the NEU classes will probably NOT improve. NEU-DET is 200x200
    grayscale, GC10-DET is 2048x1000; trained jointly at 640 one is upscaled
    3.2x and the other downscaled 3.2x. Multi-domain interference is likely.
  * The gain, if any, is in vocabulary COVERAGE: 16 queryable defect types
    instead of 6.

Class naming: the two datasets share the concept "inclusion". They are kept as
distinct label identities - NEU's stays `inclusion`, GC10's is `gc10_inclusion`
(namespaced back in Phase 1b). Both names already exist in
prompts/defect_corpus.json, so no corpus edit is needed.

Run:
    python scripts/prepare_combined.py
"""

import shutil
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from tgfem.data import GC10_CLASSES, NEU_CLASSES  # noqa: E402

NEU = REPO_ROOT / "datasets" / "neu-det-yolo"
GC10 = REPO_ROOT / "datasets" / "gc10-det-yolo"
OUT = REPO_ROOT / "datasets" / "combined-yolo"

# 16 classes: NEU's 6 first (indices 0-5, unchanged from the NEU-only runs so
# per-class numbers stay directly comparable), then GC10's 10.
COMBINED = NEU_CLASSES + GC10_CLASSES


def remap(src_root: Path, src_classes: list[str], prefix: str, subsets: dict[str, str], stats: dict):
    """Copy images and rewrite label indices into the combined class space."""
    offset = {c: COMBINED.index(c) for c in src_classes}

    manifests: dict[str, list[str]] = {k: [] for k in subsets}
    for subset, manifest_name in subsets.items():
        manifest = src_root / manifest_name
        if not manifest.exists():
            raise SystemExit(f"missing {manifest} - run the matching prepare_*.py first")

        for line in manifest.read_text().strip().splitlines():
            rel = line.strip().lstrip("./")
            src_img = src_root / rel
            if not src_img.exists():
                stats["missing_image"] += 1
                continue

            stem = f"{prefix}_{src_img.stem}"
            dst_img = OUT / "images" / f"{stem}{src_img.suffix}"
            shutil.copy2(src_img, dst_img)

            src_lbl = src_root / "labels" / f"{src_img.stem}.txt"
            out_lines = []
            for row in src_lbl.read_text().strip().splitlines():
                parts = row.split()
                old_idx = int(parts[0])
                cls = src_classes[old_idx]
                out_lines.append(" ".join([str(offset[cls])] + parts[1:]))
                stats["per_class"][cls] += 1

            (OUT / "labels" / f"{stem}.txt").write_text("\n".join(out_lines) + "\n")
            manifests[subset].append(f"./images/{stem}{src_img.suffix}")
            stats["images"] += 1

    return manifests


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "images").mkdir(parents=True)
    (OUT / "labels").mkdir(parents=True)

    print("=" * 62)
    print("Merging NEU-DET + GC10-DET -> 16 classes")
    print("=" * 62)

    stats = {"images": 0, "missing_image": 0, "per_class": Counter()}

    neu = remap(NEU, NEU_CLASSES, "neu", {
        "train": "closed_train.txt", "val": "closed_val.txt", "test": "closed_test.txt"}, stats)
    gc10 = remap(GC10, GC10_CLASSES, "gc10", {
        "train": "closed_train.txt", "val": "closed_val.txt", "test": "closed_test.txt"}, stats)

    counts = {}
    for subset in ("train", "val", "test"):
        merged = sorted(neu[subset] + gc10[subset])
        (OUT / f"combined_{subset}.txt").write_text("\n".join(merged) + "\n")
        counts[subset] = len(merged)
        print(f"  {subset:<6} {len(merged):>5} images "
              f"(neu {len(neu[subset])}, gc10 {len(gc10[subset])})")

    names = "\n".join(f"  {i}: {c}" for i, c in enumerate(COMBINED))
    (OUT / "combined_closed.yaml").write_text(
        "# Generated by scripts/prepare_combined.py - do not edit by hand.\n"
        "# NEU-DET (indices 0-5) + GC10-DET (6-15). Index order is deliberate:\n"
        "# NEU keeps its original indices so per-class results stay directly\n"
        "# comparable with the NEU-only runs.\n\n"
        f"path: {OUT.as_posix()}\n"
        "train: combined_train.txt\n"
        "val: combined_val.txt\n"
        "test: combined_test.txt\n\n"
        f"names:\n{names}\n"
    )

    print(f"\ntotal images : {stats['images']}")
    if stats["missing_image"]:
        print(f"missing      : {stats['missing_image']}")
    print(f"total boxes  : {sum(stats['per_class'].values())}")
    print("\nboxes per class:")
    for c in COMBINED:
        print(f"  {c:<18} {stats['per_class'][c]:>5}")

    print(f"\nOutput: {OUT}")
    print("Done.\n")


if __name__ == "__main__":
    main()
